### ISSUE TITLE
no module name 'libs.api'

### ISSUE THREAD

**Issue by ChenShunHsu** [hirotomusiker/CLRerNet#10]
i use the code in 'demo' file, name 'image_demo.py', but in line 7, the code 'from libs.api.inference import inference_one_image' have an error 'No module name libs.api', how should i solve this problem

**Comment by hirotomusiker** [comment]
Please refer to :
https://github.com/hirotomusiker/CLRerNet/issues/6
to set PYTHONPATH.
Thank you!

**Comment by hirotomusiker** [comment]
We close this issue as solved. If you still have a question please open another one.
