### ISSUE TITLE
Hello, when will the Culane data txt file used in this job be made public?

### ISSUE THREAD

**Issue by dongdong2061** [hirotomusiker/CLRerNet#14]

**Comment by hirotomusiker** [comment]
Thank you, we have already published the frame difference calculation script. Please try
https://github.com/hirotomusiker/CLRerNet#frame-difference-calculation
and use the calculated difference values in your dataloader to filter out redundant frames.
As we describe in our paper, we choose a threshold of 15.

**Comment by dongdong2061** [comment]
> Thank you, we have already published the frame difference calculation script. Please try https://github.com/hirotomusiker/CLRerNet#frame-difference-calculation and use the calculated difference values in your dataloader to filter out redundant frames. As we describe in our paper, we choose a threshold of 15.

When the backbone is res18, what is the accuracy of the original CLRNET on the refined dataset?

**Comment by hirotomusiker** [comment]
Unfortunately we do not include Res18 results on our experiments.

**Comment by dongdong2061** [comment]
Thanks for your help!
