### ISSUE TITLE
laneIoU loss code

### ISSUE THREAD

**Issue by lwx980315** [hirotomusiker/CLRerNet#15]
Hello, can you please share the code for your Laneiou loss? I really need it for reference. Thank you!

**Comment by hirotomusiker** [comment]
We've just started publishing loss scripts at
https://github.com/hirotomusiker/CLRerNet/tree/feature/laneiou_loss
Thank you.

**Comment by hirotomusiker** [comment]
The above branch has been merged.
Please check out:
https://github.com/hirotomusiker/CLRerNet/blob/main/libs/models/losses/iou_loss.py

Thank you.
