### ISSUE TITLE
What is the mean dash line of Acrichitecture?

### ISSUE THREAD

**Issue by yunhaklee** [hirotomusiker/CLRerNet#21]
Hello, I am very impressed with your paper.

However, I don't understand the dotted arrows pointing from x^0, y^0, theat^0 to x^1, y^1, theta^1.

Only the previous lanes that passed through the FC module are updated.
Aren’t x^0, y^0, and theat^0 unnecessary?

**Comment by yunhaklee** [comment]
First of all, thank you for the detailed answer :)

However, the lane anchor output of each stage is 192x78.

The lane anchor initially defined as the head's input is 7680 x 64 x 36 x 1.

Therefore, I am curious about how the updated anchor is combined with the anchor of the previous layer.

If I'm misunderstanding, could you tell me about each dimension?

**Comment by yunhaklee** [comment]
Thank you for your accurate, quick and very friendly response!

Also, thank you for the easy-to-read comments in the training code:)

**Comment by hirotomusiker** [comment]
Glad to be of help.
Could you ask additional questions here? 
Thank you.

**Comment by yunhaklee** [comment]
Hello, I have additional questions.


1. For the initial lane anchor, the dimension is 192x64x72.

Does this mean there are 192 lane anchors in each of the 64 channels with 72 dimensions?

2. When (xa^0, ya^0 and θa^0) passes the top stage, the output is 192x78. How does the dimension change when passed to (xa^1, ya^1 and θa^1)?

3. Additionally, lineIoU applies a constant virtual width regardless of the lane angle and the virtual lane gets ’thin’ at the tilted part -> I do not understand this part directly.


Thank you for your kind answers every time.

**Comment by hirotomusiker** [comment]
For the questions 1 and 2, probably the feature pooling should be explained:

> The anchors pool the features from the feature map (B, 64ch, H, W), obtaining (B, 192anchors, 64ch, 36 rows, 1 column).
> https://github.com/hirotomusiker/CLRerNet/blob/main/libs/models/dense_heads/clrernet_head.py#L189-L191
> The pooled features are reshaped to (B * 192 anchors, 64ch, 36 rows, 1 columns) and are fed to the head module (ROIGather).


192 lane anchors do not have feature channels. they pool the features from the feature map (see the figure below).
The pooled features are fed to ROIGather and its output becomes `fc_features` [B, 192, 64]:
https://github.com/hirotomusiker/CLRerNet/blob/main/libs/models/layers/attentions.py#L93-L117

`fc_features` [B, 192, 64] are fed to the cls and reg head and the final output is [B, 192, 78]. https://github.com/hirotomusiker/CLRerNet/blob/main/libs/models/dense_heads/clrernet_head.py#L204-L218

![image](https://github.com/hirotomusiker/CLRerNet/assets/28177967/bc40f79b-3fd5-45f8-b2f6-65b7dbd016f7)

**Comment by yunhaklee** [comment]
Thank you for your valuable reply :)
I had a lot of questions while studying, and it was a great help.
