### ISSUE TITLE
--resume-from

### ISSUE THREAD

**Issue by GH-W5** [hirotomusiker/CLRerNet#26]
`unexpected key in source state_dict: ema_backbone_model_base_layer_0_weight, ema_backbone_model_base_layer_1_weight,... `
why?

**Comment by GH-W5** [comment]
`/home/ttt/anaconda3/envs/mmseg_cd/bin/python /disk_sda/abc/Lane_Detection_project/CLRerNet/tools/train.py configs/clrernet/culane/clrernet_culane_dla34_ema.py --resume-from /disk_sda/CULane/run_work_dirs/clrernet_beijing_dla34_ema/epoch_1.pth 
`

**Comment by hirotomusiker** [comment]
Thanks, please check out the
`Resume training with ExpMomentumEMAHook` part in 
https://mmdetection.readthedocs.io/en/dev/faq.html . You need to resume the EMA weights additionally.

Adding 
`--cfg-options custom_hooks.0.resume_from={your_pth_file}`
should do the trick.

**Comment by hirotomusiker** [comment]
We close this issue as resolved.
