### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by DaDaDalong** [hirotomusiker/CLRerNet#28]
Hello, how do you test the FPS and GEflops of the CLRNET model? Can you provide some code?

**Comment by hirotomusiker** [comment]
- For FLOPs we use [mmdet tool](https://github.com/open-mmlab/mmdetection/blob/2.x/tools/analysis_tools/get_flops.py) .
- For speed test, we modified [condlanenet tool](https://github.com/aliyun/conditional-lane-detection/blob/master/tools/condlanenet/speed_test.py) a bit. We will publish the modified code later. 

Thank you.

**Comment by hirotomusiker** [comment]
@DaDaDalong We have prepared the script. Please check out the following branch:
https://github.com/hirotomusiker/CLRerNet/tree/feature/speed_test?tab=readme-ov-file#speed-test

**Comment by DaDaDalong** [comment]
Ok, thanks for your contribution and for the quick reply!
