### ISSUE TITLE
compute laneiou

### ISSUE THREAD

**Issue by zyk516** [hirotomusiker/CLRerNet#29]
Hello, according to https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/base_clrernet.py#L53, iou_dynamick uses lane_width=7.5 / 800 and  use_pred_start_end=False, but iou_cost uses lane_width=30 / 800 and use_pred_start_end=True.I want to know why they use different settings.
 Could you please explain it to me?

**Comment by hirotomusiker** [comment]
Thank you, we employ wider virtual width for the IoU cost just to balance with the classification cost. 
https://github.com/hirotomusiker/CLRerNet/blob/main/libs/core/bbox/assigners/dynamic_topk_assigner.py#L180
