### ISSUE TITLE
Hello! Thank you very much for your work on open source! I just have a question, why isn't there an experiment with resnet-18 as the backbone? In addition, what do the lane lines p and q mean in the paper?

### ISSUE THREAD

**Issue by dongdong2061** [hirotomusiker/CLRerNet#3]
![image](https://github.com/hirotomusiker/CLRerNet/assets/86656412/0aba6f07-cf4e-4ddf-8342-d1bcb7bb0d66)
``

**Comment by dongdong2061** [comment]
![~ZE9NAY~}_ M{L3 @GI@(}K](https://github.com/hirotomusiker/CLRerNet/assets/86656412/7e44f534-8657-4b78-83df-9ecbd739e0f9)

**Comment by hirotomusiker** [comment]
Thank you for reading our paper!
- We verified that performance improvement by LaneIoU was observed with different backbones, but did not include the smaller models than Res34 unfortunately.
- The lanes p and q stand for the pair of lane instances considered for IoU calculation. On some rows, lane instances (p and q) exist and intersection can be calculated (e.g. from the bottom to the top of lane B in Fig. 3). We call the set of such rows Ω<sub>pq</sub>.

**Comment by dongdong2061** [comment]
@hirotomusiker I see, thank you for your answer!
