### ISSUE TITLE
Inappropriate image size

### ISSUE THREAD

**Issue by wyyaa123** [hirotomusiker/CLRerNet#31]
Hello,  when input size is 548×412, it reports the following error during inference:
```
File "/home/nrc/CLRerNet/libs/datasets/pipelines/alaug.py", line 158, in aug
    aug = self.__augmentor(
  File "/home/nrc/CLRerNet/libs/datasets/pipelines/alaug.py", line 90, in __call__
    data_aug = self.aug(data)
  File "/home/nrc/CLRerNet/libs/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/home/nrc/CLRerNet/libs/api/inference.py", line 41, in inference_one_image
    data = test_pipeline(data)
  File "/home/nrc/CLRerNet/demo/image_demo.py", line 31, in main
    src, preds = inference_one_image(model, args.img)
  File "/home/nrc/CLRerNet/demo/image_demo.py", line 38, in <module>
    main(args)
ValueError: Values for crop should be non negative and equal or smaller than image sizes(x_min = 0, y_min = 270, x_max = 1640, y_max = 590height = 412, width = 548)
```
How can I solve this problem? Thanks! 😺
![0034_0 9_0 16](https://github.com/hirotomusiker/CLRerNet/assets/74131097/3c4e3e50-5fbb-4372-8491-4acec62793f8)

**Comment by hirotomusiker** [comment]
Could you try to change the crop region 
https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/dataset_culane_clrernet.py#L3
to the following? 
```
crop_bbox = [0, 192, 548, 412]
```
Thanks.

**Comment by wyyaa123** [comment]
> Could you try to change the crop region https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/dataset_culane_clrernet.py#L3 to the following?
> 
> ```
> crop_bbox = [0, 192, 548, 412]
> ```
> 
> Thanks.

it works, thanks!

**Comment by wyyaa123** [comment]
In addition, could you tell me why the second param is set to 192? thanks!

**Comment by hirotomusiker** [comment]
I approximately calculated the top of the crop box so that the crop_top : image_height ~= 270 : 590 (CULane setting). You can set it as you like, only if it's above the horizon line. Thanks!
