### ISSUE TITLE
failed to buildup docker container

### ISSUE THREAD

**Issue by gobears21** [hirotomusiker/CLRerNet#4]
when i try to build docker container, it failed. In my local machine, the cuda-toolkit is not installed. In addition, only python3.8 installed.
` => CACHED [21/23] WORKDIR /tmp/nms                                                                                                                                                                   0.0s
 => ERROR [22/23] RUN python /tmp/nms/setup.py install                                                                                                                                               16.6s
------                                                                                                                                                                                                     
 > [22/23] RUN python /tmp/nms/setup.py install:                                                                                                                                                           
#0 1.675 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'                                                                                                                                       
#0 1.675 running install                                                                                                                                                                                   
#0 1.881 running bdist_egg                                                                                                                                                                                 
#0 1.901 running egg_info                                                                                                                                                                                  
#0 1.906 writing src/nms.egg-info/PKG-INFO
#0 1.906 writing dependency_links to src/nms.egg-info/dependency_links.txt
#0 1.907 writing top-level names to src/nms.egg-info/top_level.txt
#0 1.931 reading manifest file 'src/nms.egg-info/SOURCES.txt'
#0 1.931 adding license file 'LICENSE'
#0 1.932 writing manifest file 'src/nms.egg-info/SOURCES.txt'
#0 1.932 installing library code to build/bdist.linux-x86_64/egg
#0 1.933 running install_lib
#0 1.933 running build_py
#0 1.933 creating build
#0 1.933 creating build/lib.linux-x86_64-cpython-38
#0 1.933 creating build/lib.linux-x86_64-cpython-38/nms
#0 1.933 copying src/nms/__init__.py -> build/lib.linux-x86_64-cpython-38/nms
#0 1.934 running build_ext
#0 2.095 building 'nms.details' extension
#0 2.095 creating build/temp.linux-x86_64-cpython-38
#0 2.095 creating build/temp.linux-x86_64-cpython-38/src
#0 2.095 gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include -I/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/TH -I/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/docker/.pyenv/versions/3.8.4/include/python3.8 -c src/nms.cpp -o build/temp.linux-x86_64-cpython-38/src/nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
#0 9.457 In file included from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
#0 9.457                  from src/nms.cpp:30:
#0 9.457 src/nms.cpp: In function ‘std::vector<at::Tensor> nms_forward(at::Tensor, at::Tensor, float, long unsigned int)’:
#0 9.457 src/nms.cpp:40:40: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
#0 9.457    40 | #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
#0 9.457       |                                        ^
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:260:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
#0 9.457   260 | #define C10_EXPAND_MSVC_WORKAROUND(x) x
#0 9.457       |                                       ^
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:280:34: note: in expansion of macro ‘C10_UNLIKELY’
#0 9.457   280 | #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
#0 9.457       |                                  ^~~~~~~~~~~~
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:332:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
#0 9.457   332 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                          \
#0 9.457       |       ^~~~~~~~~~~~~~~~~~~~~
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:627:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
#0 9.457   627 |     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__)); \
#0 9.457       |                                ^~~~~~~~~~~~~~~~~~~~~
#0 9.457 src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
#0 9.457    40 | #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
#0 9.457       |                       ^~~~~~~~~~
#0 9.457 src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
#0 9.457    42 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
#0 9.457       |                        ^~~~~~~~~~
#0 9.457 src/nms.cpp:53:5: note: in expansion of macro ‘CHECK_INPUT’
#0 9.457    53 |     CHECK_INPUT(boxes);
#0 9.457       |     ^~~~~~~~~~~
#0 9.457 In file included from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/core/Tensor.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/DeviceGuard.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/ATen.h:11,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
#0 9.457                  from src/nms.cpp:30:
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:213:30: note: declared here
#0 9.457   213 |   DeprecatedTypeProperties & type() const {
#0 9.457       |                              ^~~~
#0 9.457 In file included from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
#0 9.457                  from src/nms.cpp:30:
#0 9.457 src/nms.cpp:40:40: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
#0 9.457    40 | #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
#0 9.457       |                                        ^
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:260:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
#0 9.457   260 | #define C10_EXPAND_MSVC_WORKAROUND(x) x
#0 9.457       |                                       ^
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:280:34: note: in expansion of macro ‘C10_UNLIKELY’
#0 9.457   280 | #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
#0 9.457       |                                  ^~~~~~~~~~~~
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:332:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
#0 9.457   332 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                          \
#0 9.457       |       ^~~~~~~~~~~~~~~~~~~~~
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:627:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
#0 9.457   627 |     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__)); \
#0 9.457       |                                ^~~~~~~~~~~~~~~~~~~~~
#0 9.457 src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
#0 9.457    40 | #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
#0 9.457       |                       ^~~~~~~~~~
#0 9.457 src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
#0 9.457    42 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
#0 9.457       |                        ^~~~~~~~~~
#0 9.457 src/nms.cpp:54:5: note: in expansion of macro ‘CHECK_INPUT’
#0 9.457    54 |     CHECK_INPUT(idx);
#0 9.457       |     ^~~~~~~~~~~
#0 9.457 In file included from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/core/Tensor.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/DeviceGuard.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/ATen.h:11,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
#0 9.457                  from /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
#0 9.457                  from src/nms.cpp:30:
#0 9.457 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:213:30: note: declared here
#0 9.457   213 |   DeprecatedTypeProperties & type() const {
#0 9.457       |                              ^~~~
#0 16.33 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
#0 16.33 !!
#0 16.33 
#0 16.33         ********************************************************************************
#0 16.33         Please avoid running ``setup.py`` directly.
#0 16.33         Instead, use pypa/build, pypa/installer or other
#0 16.33         standards-based tools.
#0 16.33 
#0 16.33         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
#0 16.33         ********************************************************************************
#0 16.33 
#0 16.33 !!
#0 16.33   self.initialize_options()
#0 16.33 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
#0 16.33 !!
#0 16.33 
#0 16.33         ********************************************************************************
#0 16.33         Please avoid running ``setup.py`` and ``easy_install``.
#0 16.33         Instead, use pypa/build, pypa/installer or other
#0 16.33         standards-based tools.
#0 16.33 
#0 16.33         See https://github.com/pypa/setuptools/issues/917 for details.
#0 16.33         ********************************************************************************
#0 16.33 
#0 16.33 !!
#0 16.33   self.initialize_options()
#0 16.33 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
#0 16.33   warnings.warn(msg.format('we could not find ninja.'))
#0 16.33 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
#0 16.33   warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
#0 16.33 /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
#0 16.33   warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
#0 16.34 Traceback (most recent call last):
#0 16.34   File "/tmp/nms/setup.py", line 5, in <module>
#0 16.34     setup(
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
#0 16.34     return distutils.core.setup(**attrs)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 16.34     return run_commands(dist)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 16.34     dist.run_commands()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 16.34     self.run_command(cmd)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
#0 16.34     super().run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 16.34     cmd_obj.run()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/install.py", line 80, in run
#0 16.34     self.do_egg_install()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/install.py", line 129, in do_egg_install
#0 16.34     self.run_command('bdist_egg')
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 16.34     self.distribution.run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
#0 16.34     super().run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 16.34     cmd_obj.run()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
#0 16.34     cmd = self.call_command('install_lib', warn_dir=0)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
#0 16.34     self.run_command(cmdname)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 16.34     self.distribution.run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
#0 16.34     super().run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 16.34     cmd_obj.run()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
#0 16.34     self.build()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
#0 16.34     self.run_command('build_ext')
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 16.34     self.distribution.run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
#0 16.34     super().run_command(command)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 16.34     cmd_obj.run()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
#0 16.34     _build_ext.run(self)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
#0 16.34     self.build_extensions()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
#0 16.34     build_ext.build_extensions(self)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
#0 16.34     self._build_extensions_serial()
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
#0 16.34     self.build_extension(ext)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
#0 16.34     _build_ext.build_extension(self, ext)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 127, in build_extension
#0 16.34     super(build_ext, self).build_extension(ext)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
#0 16.34     objects = self.compiler.compile(
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
#0 16.34     self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 513, in unix_wrap_single_compile
#0 16.34     cflags = unix_cuda_flags(cflags)
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
#0 16.34     cflags + _get_cuda_arch_flags(cflags))
#0 16.34   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
#0 16.34     arch_list[-1] += '+PTX'
#0 16.34 IndexError: list index out of range
------
failed to solve: process "/bin/sh -c python /tmp/nms/setup.py install" did not complete successfully: exit code: 1
`

**Comment by PINTO0309** [comment]
```bash
git clone https://github.com/hirotomusiker/CLRerNet.git \
&& cd CLRerNet

docker build \
--no-cache \
--build-arg UID="`id -u`" \
--build-arg PYTHON_VERSION="3.8.4" \
--build-arg TORCH_VERSION="1.12.1+cu116" \
--build-arg TORCHVISION_VERSION="0.13.1" \
--build-arg TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6" \
--build-arg MIM_VERSION="0.3.3" \
--build-arg MMCV_VERSION="1.7.0" \
--build-arg MMDET_VERSION="2.28.0" \
--build-arg TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6" \
-f docker/Dockerfile \
-t dev .
```

**Comment by hirotomusiker** [comment]
@gobears21 Thank you, did you try it with the latest commit (after [779e0be](https://github.com/hirotomusiker/CLRerNet/commit/779e0bebd85a4d0bcc31b39ac4512fccfc6fbcae))?
Please let us know the build command.

**Comment by gobears21** [comment]
Thank you very much for your prompt reply.

I can build the docker now. In the meantime, I have some additional inquiries.

- May I ask where I can download the pre-trained weight? (in this case, the file named `clrernet_culane_dla34_ema.pth` )

- The training method seems not public yet, I am expecting to try it.
 
- It seems your https repository has some problem. I can not clone it in HTTPS (works on ssh)
`git clone https://github.com/hirotomusiker/CLRerNet.git                             
Cloning into 'CLRerNet'...                                                                                            
fatal: protocol error: bad line length 215                                                                            
fatal: The remote end hung up unexpectedly `

**Comment by PINTO0309** [comment]
![image](https://github.com/hirotomusiker/CLRerNet/assets/33194443/e5b49576-7849-4774-ac7c-80253fdca1c3)
https://github.com/hirotomusiker/CLRerNet/releases

```
docker run --rm -it \
--gpus all \
-v `pwd`:/work \
--shm-size 16gb
```

>It seems your https repository has some problem. I can not clone it in HTTPS (works on ssh)

It could be a problem with your network or the version of the git command. It is not reproducible.

**Comment by gobears21** [comment]
sorry again, but the inference seems not working.

Input:
docker@17cbb1917658:~/CLRerNet$ python demo/image_demo.py demo/demo.jpg configs/clrernet/culane/clrernet_culane_dla34_ema.py clrernet_culane_dla34_ema.pth --out-file=result.png   

Output:
/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)                                  
return torch._C._cuda_getDeviceCount() > 0                                          No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'                           /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.    warnings.warn(                                                                      load checkpoint from local path: clrernet_culane_dla34_ema.pth                        /home/docker/mmdetection/mmdet/apis/inference.py:51: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.                       warnings.warn('Class names are not saved in the checkpoint\'s '                     Traceback (most recent call last):                                                      File "demo/image_demo.py", line 36, in <module>                                         main(args)                                                                          File "demo/image_demo.py", line 27, in main                                             model = init_detector(args.config, args.checkpoint, device=args.device)             File "/home/docker/mmdetection/mmdet/apis/inference.py", line 55, in init_detector      model.to(device)                                                                    File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to                                                             return self._apply(convert)                                                         File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply                                                         module._apply(fn)                                                                   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply                                                         module._apply(fn)                                                                   File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply                                                         module._apply(fn)                                                                   [Previous line repeated 1 more time]                                                  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply                                                         param_applied = fn(param)                                                           File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert                                                        return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)                                                                             File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init                                                         torch._C._cuda_init()                                                             RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW

**Comment by PINTO0309** [comment]
Depends on the model number of your GPU.

```
lspci | grep -i VGA
```

https://developer.nvidia.com/cuda-gpus

![image](https://github.com/hirotomusiker/CLRerNet/assets/33194443/e609850d-f13c-49b1-9839-ad07001cc3fc)

You need to change the numbers below to match your GPU and do the docker build again
```
--build-arg TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6"
```

**Comment by hirotomusiker** [comment]
We are closing this issue as solved. If you still have a question please open another one.
