### ISSUE TITLE
the exact versions of MMCV and MMDet

### ISSUE THREAD

**Issue by masyrezaei** [hirotomusiker/CLRerNet#44]
Hi, Could you please tell me the exact versions of MMCV and MMDet? I'm encountering an error with these packages. Thanks

**Comment by hirotomusiker** [comment]
The exact mmcv / mmdet versions are specified here:
https://github.com/hirotomusiker/CLRerNet/blob/main/docker-compose.yaml#L13-L15
Thank you!
