### ISSUE TITLE
AttributeError: module 'mmdet' has no attribute 'LOSSES'

### ISSUE THREAD

**Issue by jinmeijian** [hirotomusiker/CLRerNet#47]
你好，我没有用docker。用issues中的pip安装包并且install成功了。我运行 python tools/train.py configs/clrernet/culane/clrernet_culane_dla34.py
这个代码的时候出现了这个错误。我用的这个pip install torch==1.12.1+cu116 torchvision==0.13.1 torchaudio -f https://download.pytorch.org/whl/torch_stable.html
pip install -U openmim
mim install mmcv-full==1.7.0
pip install mmdet==2.28.0
pip install wandb
pip install tensorboard
pip install albumentations==0.4.6
pip install p_tqdm==1.3.3
pip install pytest
pip install pytest-cov
cd libs/models/layers/nms/
python setup.py install

您能当我解惑吗

**Comment by hirotomusiker** [comment]
Could you please rewrite your question in English, and paste the whole error message if possible?
thank you.

**Comment by jinmeijian** [comment]
I've resolved the issue myself, and thank you for your response.
