### ISSUE TITLE
How to integrate the LaneIoU loss function from CLRerNet into the LaneATT architecture?

### ISSUE THREAD

**Issue by XiaoCangbit** [hirotomusiker/CLRerNet#48]
Hello! Could you kindly assist me in integrating the LaneIoU loss function from CLRerNet into the LaneATT architecture? Additionally, could you guide me on where I might find the relevant code?
Thank you in advance for your help.

**Comment by hirotomusiker** [comment]
Thank you.

We described an effective LaneATT + LaneIoU setting in the [supplementary material.](https://openaccess.thecvf.com/content/WACV2024/supplemental/Honda_CLRerNet_Improving_Confidence_WACV_2024_supplemental.pdf)

Positive and negative anchors are calculated separately for classification loss and regression loss, and LaneIoU is employed only for the former. The anchors whose max IoU with GTs is over 0.7 (under 0.5) are regarded as positive (negative) and the classification target is set to 1 (0). (ref: [LaneATT matching function](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/matching.py))

We don't see significant improvement when LaneIoU is applied for regression loss.

**Comment by hirotomusiker** [comment]
We will publish LaneIoU-aware `match_proposals_with_targets` function later for reference.

**Comment by songyonger** [comment]
Hi, can you tell me where is the LaneIoU-aware match_proposals_with_targets function for reference? @XiaoCangbit @hirotomusiker

**Comment by hirotomusiker** [comment]
Check this out:
https://github.com/hirotomusiker/CLRerNet/tree/feature/laneatt/configs/laneatt
