### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by yunmengmengyun** [hirotomusiker/CLRerNet#50]
Dear authors,

Thanks for your work. 
If I want to run the models on my own images, what configurations do I need to change to achieve the best performance?
currently, I know I need to change the ori img sizes and crop bbox. is there any other parameters I need to configure?

Because I found the model doesn't work well for the broken lane markings. 

Thanks in advance!!!!!!!!!!!!!!

**Comment by hirotomusiker** [comment]
We firstly recommend to adjust (decrease) the [confidence threshold](https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/clrernet_culane_dla34_ema.py#L21) to detect unclear lanes.

Second, check if the maximum number of outputs
https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/base_clrernet.py#L48
is less than the outputs you need to detect at once.

Thank you.

**Comment by yunmengmengyun** [comment]
Thanks a lot!!!
