### ISSUE TITLE
how to set test batchsize?

### ISSUE THREAD

**Issue by RDXiaoLu** [hirotomusiker/CLRerNet#51]
I need test batchsize set 16. but how to do this?

**Comment by hirotomusiker** [comment]
I can't check it right now but could you check if it works by changing the following part? 
https://github.com/hirotomusiker/CLRerNet/blob/2b5632b55871b321080cce8069b01297b8134739/tools/test.py#L165

**Comment by RDXiaoLu** [comment]
Only set 1,  other set will report error.   The reason is  function simple_test
