### ISSUE TITLE
Is docker environment necessary for train?

### ISSUE THREAD

**Issue by AtharzWang** [hirotomusiker/CLRerNet#7]
Hi, I'm new to docker. Usually I use conda environment to train and inference. Do you have the conda or pip version requirements.txt? 
Thx.

**Comment by hirotomusiker** [comment]
Thank you, please refer to 
https://github.com/hirotomusiker/CLRerNet/issues/6
for non-docker installation at the moment :)

**Comment by hirotomusiker** [comment]
We close this issue as solved. If you still have a question please open another one.
