### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by hthanhle** [hirotomusiker/CLRerNet#8]
Could you kindly release the training code? It would be very helpful for my urgent work. Many thanks.

**Comment by hirotomusiker** [comment]
We are planning to release a script for frame difference calculation to filter out redundant frames, but it'll take more time to prepare the whole training codebase. Thank you.

**Comment by baiyancheng20** [comment]
Hi, when will you release the training code?  Is there any plan?

**Comment by hirotomusiker** [comment]
We have prepared the training codebase in the following branch :
https://github.com/hirotomusiker/CLRerNet/tree/feature/train
please check it out.
