### ISSUE TITLE
Curvelanes

### ISSUE THREAD

**Issue by WangLu95** [hirotomusiker/CLRerNet#9]
I have carefully read your article and found that you conducted comparative experiments on the Curvelanes dataset. I am currently using CLRNet for this dataset, but it can only reach 73. I think there may be issues with data loading or parameter settings. So could you please also disclose the test code for the CurveLanes dataset? Thank you very much.

**Comment by hirotomusiker** [comment]
Thank you, we don't have a plan to publish the code for CurveLanes soon, however you can refer to the scripts we have employed for the experiments:

https://github.com/aliyun/conditional-lane-detection/blob/master/mmdet/datasets/curvelanes_dataset.py
https://github.com/aliyun/conditional-lane-detection/blob/master/tools/condlanenet/lane_metric.py

Note that we have used the evaluation resolution of (224, 224) and line width of 5, and that CurveLanes typically has more than 4 GT lanes per image.

**Comment by hirotomusiker** [comment]
Thank you,
Please refer to https://github.com/hirotomusiker/CLRerNet/issues/9  for more information regarding training on Curvelanes.
